### PR TITLE
Used Base Template for Payment Method and Payment Successful (Added order id in payment Successful page as well)

### PR DESCRIPTION
**Pull request by Singhmeghna**
Used Base Template for Payment Method and Payment Successful (Added order id in payment Successful page as well)

### CODE REVIEW

**Comment by prithvi211100** [comment]
Screenshot 2024-07-21 at 3 59 11 PM

Getting operational error when clicking on 'checkout' button at checkout page. It is working in master branch

**Review by prithvi211100 — COMMENTED** [review]
please verify

**Review by nishmr22 — COMMENTED** [review]
Server error. Throwing error during the payment completion. Resolve this

**Comment by Singhmeghna** [comment]
Closing this PR and raising a new one with corrections.

**Pull request closed without merging**
